# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-17 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('henry', '0002_auto_20170817_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notmanaged',
            options={'managed': False},
        ),
    ]
